### PR TITLE
Update zio version to 1.0.6

### PR DESCRIPTION
**Pull request by alphaho**
Just found ZIO 1.0.6 is too new to be supported in IntelliJ:

image

image

### CODE REVIEW

**Comment by hmemcpy** [comment]
Thank you! Can you also bump the Scala 3 version to RC2? In the yaml and wherever else it's defined.

**Comment by alphaho** [comment]
Sure! Let me make the change

**Comment by hmemcpy** [comment]
Cheers! I'm not on the computer right now, I'll tag this with 1.0.6 when CI passes!

**Comment by alphaho** [comment]
No hurry. Feel free to do it at your convenience :-)

**Comment by hmemcpy** [comment]
Looks great! Thanks again!

**Comment by alphaho** [comment]
Thanks! Now the test runner can be successfully downloaded! 
image

**Pull request merged**
